### ISSUE TITLE
Issue for ML-Decoder:Experimental results of CP / CR/ CF1 and other metrics on MS-COCO 2014 data set #20

### ISSUE THREAD

**Issue by aliman80** [mymuli/Deep-Learning-Notes#1]
Hi , 
Thank you for sharing your great work. I have seen your issue mentioned in ML-Decoder. I am working on zsl and want to compute F1 score for k=3 and K=5 values as given in paper . Can you please share your code to compute these parameters.

Regards

**Comment by mymuli** [comment]
For the formula for calculating CP/CR/CF1, please refer to the following link:

https://github.com/QData/C-Tran/blob/236d785952c59210e6812b4ad5ee12bab585ce4c/utils/evaluate.py#L75

**Comment by aliman80** [comment]
Thanks very much
